name: AmbulanceGame
channels:
  - defaults
dependencies:
  - pip==20.2.4
  - sympy==1.5.1
  - scipy==1.4.1
  - numpy==1.19.2
  - python==3.8.1
  - notebook==6.0.3
  - pylint==2.4.4
  - matplotlib==3.3.2
  - seaborn==0.10.0
  - ipykernel==5.3.4
  - networkx==2.4
  - dask==2021.3.0
  - pip:
      - ciw==2.1.0
prefix: C:\Users\micha\Anaconda3\envs\AmbulanceGame
